name: gobabel
description: Translate your api with only one cli command.
version: 0.0.1
repository: https://github.com/Go-Babel/gobabel
issue: https://github.com/Go-Babel/gobabel/issues
publish_to: 'none'

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4
  enchanted_regex: ^1.0.7
  # intl_translation: ^0.20.1
  json_annotation: ^4.9.0
  collection: ^1.19.1
  git: ^2.3.1
  analyzer: ^7.4.5
  dio: ^5.8.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  enchanted_collection: ^1.3.0
  http: ^1.3.0
  recase: ^4.1.0
  process_run: ^1.2.4
  gobabel_core:
    path: ../gobabel_core
  gobabel_client:
    path: ../go_babel_app/gobabel_client
  gobabel_string_extractor:
    path: ../gobabel_string_extractor
  yaml: ^3.1.3
  args:  2.7.0
  console_bars: ^1.2.0
  chalkdart: ^3.0.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.5
