name: gobabel
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  freezed_annotation: ^2.4.4
  intl_translation: ^0.20.1
  json_annotation: ^4.9.0
  collection: ^1.19.1
  result_dart: ^2.0.0
  git: ^2.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  enchanted_collection: ^1.3.0
  console_bars: ^1.2.0
  http: ^1.3.0
  recase: ^4.1.0
  process_run: ^1.2.4
  gobabel_core:
    path: ../gobabel_core
  gobabel_client:
    path: ../go_babel_app/gobabel_client

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
