name: gobabel
description: Translate your api with only one cli command.
version: 0.0.1
repository: https://github.com/Go-Babel/gobabel
issue: https://github.com/Go-Babel/gobabel/issues
# Ready to publish to pub.dev when needed
# publish_to: 'https://pub.dev'

environment:
  sdk: ^3.8.1

resolution: workspace

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  enchanted_regex: ^1.0.7
  # intl_translation: ^0.20.1
  collection: ^1.19.1
  result_dart: ^2.1.1
  git: ^2.3.1
  meta: ^1.17.0
  analyzer: ^7.4.5
  crypto: ^3.0.6
  dio: ^5.8.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  enchanted_collection: ^1.3.0
  http: ^1.3.0
  recase: ^4.1.0
  process_run: ^1.2.4
  gobabel_core: any
  gobabel_client: any
  yaml: ^3.1.3
  args:  2.7.0
  chalkdart: ^3.0.5
  dart_console: ^4.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  freezed: ^3.2.0
  build_runner: ^2.6.1
  json_serializable: ^6.10.0
